// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleSales;

#nullable disable

namespace VehicleSales.Migrations
{
    [DbContext(typeof(VehicleSalesDbContext))]
    [Migration("20260224150744_CreateVehicleSale")]
    partial class CreateVehicleSale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VehicleSales.Entities.User.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("Users", (string)null);
                });

            modelBuilder.Entity("VehicleSales.Entities.VehicleMake.VehicleMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("vehicle_makes", (string)null);
                });

            modelBuilder.Entity("VehicleSales.Entities.VehicleMake.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("VehicleMakeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleMakeId");

                    b.HasIndex("Name", "VehicleMakeId")
                        .IsUnique();

                    b.ToTable("vehicle_models", (string)null);
                });

            modelBuilder.Entity("VehicleSales.Entities.VehicleSale.VehicleSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Sale", "VehicleSales.Entities.VehicleSale.VehicleSale.Sale#Sale", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("CreatedAt");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("VARCHAR(5000)")
                                .HasColumnName("Description");

                            b1.Property<int>("Status")
                                .HasColumnType("int")
                                .HasColumnName("Status");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("Title");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("UpdatedAt");

                            b1.ComplexProperty<Dictionary<string, object>>("Location", "VehicleSales.Entities.VehicleSale.VehicleSale.Sale#Sale.Location#Location", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("County")
                                        .IsRequired()
                                        .HasColumnType("VARCHAR(100)")
                                        .HasColumnName("County");

                                    b2.Property<string>("Locality")
                                        .IsRequired()
                                        .HasColumnType("VARCHAR(100)")
                                        .HasColumnName("Locality");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("SalePrice", "VehicleSales.Entities.VehicleSale.VehicleSale.Sale#Sale.SalePrice#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("AmountInCents")
                                        .HasColumnType("int")
                                        .HasColumnName("AmountInCents");

                                    b2.Property<int>("Currency")
                                        .HasColumnType("int")
                                        .HasColumnName("Currency");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("vehicle_sales", (string)null);
                });

            modelBuilder.Entity("VehicleSales.Entities.VehicleMake.VehicleModel", b =>
                {
                    b.HasOne("VehicleSales.Entities.VehicleMake.VehicleMake", "VehicleMake")
                        .WithMany("VehicleModels")
                        .HasForeignKey("VehicleMakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleMake");
                });

            modelBuilder.Entity("VehicleSales.Entities.VehicleSale.VehicleSale", b =>
                {
                    b.HasOne("VehicleSales.Entities.User.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VehicleSales.Entities.VehicleSale.VehicleDetails", "VehicleDetails", b1 =>
                        {
                            b1.Property<int>("VehicleSaleId")
                                .HasColumnType("int");

                            b1.Property<ushort?>("AverageBatteryConsumptionInKWhPer100Km")
                                .HasColumnType("smallint unsigned")
                                .HasColumnName("AverageBatteryConsumptionInKWhPer100Km");

                            b1.Property<uint?>("AverageFuelConsumptionInLitersPer100Km")
                                .HasColumnType("int unsigned")
                                .HasColumnName("AverageFuelConsumptionInLitersPer100Km");

                            b1.Property<uint?>("BatteryCapacityInKWh")
                                .HasColumnType("int unsigned")
                                .HasColumnName("BatteryCapacityInKWh");

                            b1.Property<int?>("BodyType")
                                .HasColumnType("int")
                                .HasColumnName("BodyType");

                            b1.Property<int?>("DriveType")
                                .HasColumnType("int")
                                .HasColumnName("DriveType");

                            b1.Property<int?>("EmissionStandard")
                                .HasColumnType("int")
                                .HasColumnName("EmissionStandard");

                            b1.Property<uint?>("EngineVolumeInCm3")
                                .HasColumnType("int unsigned")
                                .HasColumnName("EngineVolumeInCm3");

                            b1.Property<string>("ExteriorColor")
                                .HasColumnType("VARCHAR(30)")
                                .HasColumnName("ExteriorColor");

                            b1.Property<int?>("FuelType")
                                .HasColumnType("int")
                                .HasColumnName("FuelType");

                            b1.Property<int?>("GearboxType")
                                .HasColumnType("int")
                                .HasColumnName("GearboxType");

                            b1.Property<bool?>("HasAccidentHistory")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("HasAccidentHistory");

                            b1.Property<bool?>("HasServiceHistory")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("HasServiceHistory");

                            b1.Property<uint?>("HorsePower")
                                .HasColumnType("int unsigned")
                                .HasColumnName("HorsePower");

                            b1.Property<string>("InteriorColor")
                                .HasColumnType("VARCHAR(30)")
                                .HasColumnName("InteriorColor");

                            b1.Property<uint?>("Mass")
                                .HasColumnType("int unsigned")
                                .HasColumnName("Mass");

                            b1.Property<uint?>("MaximumLoad")
                                .HasColumnType("int unsigned")
                                .HasColumnName("MaximumLoad");

                            b1.Property<uint?>("MileageInKilometers")
                                .HasColumnType("int unsigned")
                                .HasColumnName("MileageInKilometers");

                            b1.Property<ushort?>("NumberOfPreviousOwners")
                                .HasColumnType("smallint unsigned")
                                .HasColumnName("NumberOfPreviousOwners");

                            b1.Property<int?>("NumberOfSeats")
                                .HasColumnType("int")
                                .HasColumnName("NumberOfSeats");

                            b1.Property<uint?>("RangeInKilometers")
                                .HasColumnType("int unsigned")
                                .HasColumnName("RangeInKilometers");

                            b1.Property<int?>("SteeringWheelSide")
                                .HasColumnType("int")
                                .HasColumnName("SteeringWheelSide");

                            b1.Property<int?>("VehicleCondition")
                                .HasColumnType("int")
                                .HasColumnName("VehicleCondition");

                            b1.Property<int?>("VehicleManufacturingYear")
                                .HasColumnType("int")
                                .HasColumnName("VehicleManufacturingYear");

                            b1.Property<int>("VehicleModelId")
                                .HasColumnType("int")
                                .HasColumnName("VehicleModelId");

                            b1.Property<int?>("VehicleNumberOfDoors")
                                .HasColumnType("int")
                                .HasColumnName("VehicleNumberOfDoors");

                            b1.Property<string>("VehicleVersion")
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("VehicleVersion");

                            b1.Property<string>("Vin")
                                .HasColumnType("VARCHAR(17)")
                                .HasColumnName("Vin");

                            b1.HasKey("VehicleSaleId");

                            b1.HasIndex("VehicleModelId");

                            b1.ToTable("vehicle_sales");

                            b1.HasOne("VehicleSales.Entities.VehicleMake.VehicleModel", "VehicleModel")
                                .WithMany()
                                .HasForeignKey("VehicleModelId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("VehicleSaleId");

                            b1.Navigation("VehicleModel");
                        });

                    b.Navigation("Seller");

                    b.Navigation("VehicleDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleSales.Entities.VehicleMake.VehicleMake", b =>
                {
                    b.Navigation("VehicleModels");
                });
#pragma warning restore 612, 618
        }
    }
}
