@baseUrl = http://192.168.0.21:5153
@bearerToken = ...

###
GET {{baseUrl}}

###
POST {{baseUrl}}/account/register
Content-Type: application/json

{
    "email": "test1@example.com",
    "password": "passs1Ddsfs#"
}

###
GET {{baseUrl}}/account/confirm-email?token=

###
POST {{baseUrl}}/account/login
Content-Type: application/json

{
    "email": "test1@example.com",
    "password": "passs1Ddsfs#"
}

###
POST {{baseUrl}}/refresh-token
Content-Type: application/json

{
    "refreshToken": ""
}

###
GET {{baseUrl}}/account/health
Authorization: Bearer ...

###
GET {{baseUrl}}/account/profile
Authorization: Bearer ...

###
GET {{baseUrl}}/vehicle-sales/makes

###
GET {{baseUrl}}/vehicle-sales/models?makeName=bmw

###
PUT https://vehicle-sales.32d6a197b805a198a142c29a53469f77.r2.cloudflarestorage.com/a58e8def-ae2a-44df-84ad-/0.jpeg?X-Amz-Expires=900&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=6830be008a560c9b5cc566f1431b2d34%2F20260227%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260227T204049Z&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Signature=8c7dbcbcdc2f96ee500f10c155011043aa85350230427500898a800ed0ba37a7
Content-Type: image/jpeg

< C:\Users\janos.laszlo\Downloads\profile photo.jpeg

###
POST {{baseUrl}}/vehicle-sales
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "title": "2019 BMW 3 Series - Excellent Condition",
  "description": "Well maintained 2019 BMW 3 Series with full service history. One previous owner, no accidents. Comes with winter tires and original floor mats.",
  "amountInCents": 2499900,
  "currency": "EUR",
  "county": "Los Angeles",
  "locality": "Santa Monica",
  "vehicleModelId": 6200,
  "mileageInKilometers": 45000,
  "horsePower": 255,
  "vehicleVersion": "Sport Line",
  "bodyType": "Sedan",
  "engineVolumeInCm3": 1998,
  "exteriorColor": "Alpine White",
  "interiorColor": "Black",
  "fuelType": "Petrol",
  "vehicleManufacturingYear": 2019,
  "vehicleNumberOfDoors": 4,
  "vehicleCondition": "Used",
  "gearboxType": "Automatic",
  "steeringWheelSide": "Left",
  "driveType": "RearWheelDrive",
  "numberOfSeats": 5,
  "emissionStandard": "EURO6",
  "hasServiceHistory": true,
  "hasAccidentHistory": false,
  "vin": "WBA5R1C50KAK12345",
  "numberOfPreviousOwners": 1,
  "batteryCapacityInKWh": 11000,
  "rangeInKilometers": 1000,
  "averageFuelConsumptionInLitersPer100Km": 6,
  "averageBatteryConsumptionInKWhPer100Km": 90,
  "massInKg": 1520,
  "maximumLoadInKg": 480
}

###
PATCH {{baseUrl}}/vehicle-sales/confirm-object-upload/1
Authorization: Bearer {{bearerToken}}

###
GET {{baseUrl}}/vehicle-sales?pageNumber=0&pageSize=10
Authorization: Bearer {{bearerToken}}

###
PATCH {{baseUrl}}/vehicle-sales/1
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "vin": "WBA5R1C50KAK54321"
}
