GET http://localhost:5152

###
GET http://localhost:5152/todos

###
POST http://localhost:5152/register
Content-Type: application/json

{
    "email": "test2@example.com",
    "password": "passs1Ddsfs#"
}

###
POST http://localhost:5152/login
Content-Type: application/json

{
    "email": "test2@example.com",
    "password": "passs1Ddsfs#"
}

###
POST http://localhost:5152/refresh-token
Content-Type: application/json

{
    "refreshToken": "CfDJ8Oh10UJTx_1DhG3oXzBOYDdWgfa8NRHTZACFOKENNKvrd8tD9BGClXbu4yVEMCa6xqpk6cC4XGC063YES6bZpX3b3iNcY9lJlV9Al0mHfbnMKbD3Xqfv1slShclXzkuxLFmJD90qcZxyukQ46aiGOU3TywZi1WjyEEtadaY2c3PeeqO1d4-0-OJ_bECStc-POg"
}

###
GET http://localhost:5152/health
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUxNTIiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUxNTIiLCJleHAiOjE3NjkwNDA4NTgsImlhdCI6MTc2OTAzMzY1OCwibmJmIjoxNzY5MDMzNjU4LCJzdWIiOjIsImVtYWlsIjoidGVzdDJAZXhhbXBsZS5jb20ifQ.1M_51pds6t5-JzcQnR1LZCMLfvPpmAyAZB7-yJSQKkQ
