// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObjectUploadTracking;

#nullable disable

namespace ObjectUploadTracking.Migrations
{
    [DbContext(typeof(ObjectUploadTrackingDbContext))]
    [Migration("20260305222557_CreateObjectUpload")]
    partial class CreateObjectUpload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ObjectUploadTracking.ObjectUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("Directory");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("ObjectKeys")
                        .IsRequired()
                        .HasColumnType("VARCHAR(109)")
                        .HasColumnName("ObjectKeys");

                    b.HasKey("Id");

                    b.ToTable("object_uploads", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
